[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/up"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true" 