/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/views/**/*.html.erb',
    './app/helpers/**/*.rb',
    './app/assets/stylesheets/**/*.css',
    './app/javascript/**/*.js',
    './app/javascript/**/*.ts'
  ],
  theme: {
    extend: {
      colors: {
        // Scorecard Brand Colors
        'scorecard': {
          'green': {
            50: '#f0f9f4',
            100: '#dcf4e3', 
            200: '#bbe8ca',
            300: '#86d5a1',
            400: '#4aba6f',
            500: '#22a047', // Primary brand green
            600: '#1a7f38',
            700: '#176530',
            800: '#16522a',
            900: '#134425',
          },
          'gold': {
            50: '#fefcf0',
            100: '#fef7d9',
            200: '#fdeeb3',
            300: '#fce083',
            400: '#fac951', // Secondary brand gold
            500: '#f8b82e',
            600: '#ed9516',
            700: '#c57212',
            800: '#9d5916',
            900: '#7f4917',
          }
        },
        // Enhanced greens for golf theme
        'golf': {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0', 
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        }
      },
      fontFamily: {
        'scorecard': ['Inter', 'system-ui', 'sans-serif'],
        'heading': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'scorecard-xs': ['0.75rem', { lineHeight: '1rem' }],
        'scorecard-sm': ['0.875rem', { lineHeight: '1.25rem' }], 
        'scorecard-base': ['1rem', { lineHeight: '1.5rem' }],
        'scorecard-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'scorecard-xl': ['1.25rem', { lineHeight: '1.75rem' }],
        'scorecard-2xl': ['1.5rem', { lineHeight: '2rem' }],
        'scorecard-3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      }
    },
  },
  plugins: [],
  safelist: [
    // Existing classes
    'opacity-0',
    'opacity-100',
    'group-hover:opacity-100',
    'transition-opacity',
    'duration-200',
    'pointer-events-none',
    'absolute',
    'bottom-full',
    'left-1/2',
    'transform',
    '-translate-x-1/2',
    'mb-2',
    'px-3',
    'py-2',
    'bg-gray-900',
    'text-white',
    'text-xs',
    'rounded-lg',
    'w-64',
    'z-10',
    // Brand colors - ensure they're generated
    'bg-scorecard-green-50',
    'bg-scorecard-green-100',
    'bg-scorecard-green-200',
    'bg-scorecard-green-300',
    'bg-scorecard-green-400',
    'bg-scorecard-green-500',
    'bg-scorecard-green-600',
    'bg-scorecard-green-700',
    'bg-scorecard-green-800',
    'bg-scorecard-green-900',
    'bg-scorecard-gold-50',
    'bg-scorecard-gold-100',
    'bg-scorecard-gold-200',
    'bg-scorecard-gold-300',
    'bg-scorecard-gold-400',
    'bg-scorecard-gold-500',
    'bg-scorecard-gold-600',
    'bg-scorecard-gold-700',
    'bg-scorecard-gold-800',
    'bg-scorecard-gold-900',
    'text-scorecard-green-50',
    'text-scorecard-green-100',
    'text-scorecard-green-200',
    'text-scorecard-green-300',
    'text-scorecard-green-400',
    'text-scorecard-green-500',
    'text-scorecard-green-600',
    'text-scorecard-green-700',
    'text-scorecard-green-800',
    'text-scorecard-green-900',
    'text-scorecard-gold-50',
    'text-scorecard-gold-100',
    'text-scorecard-gold-200',
    'text-scorecard-gold-300',
    'text-scorecard-gold-400',
    'text-scorecard-gold-500',
    'text-scorecard-gold-600',
    'text-scorecard-gold-700',
    'text-scorecard-gold-800',
    'text-scorecard-gold-900',
    'border-scorecard-green-50',
    'border-scorecard-green-100',
    'border-scorecard-green-200',
    'border-scorecard-green-300',
    'border-scorecard-green-400',
    'border-scorecard-green-500',
    'border-scorecard-green-600',
    'border-scorecard-green-700',
    'border-scorecard-green-800',
    'border-scorecard-green-900',
    'border-scorecard-gold-50',
    'border-scorecard-gold-100',
    'border-scorecard-gold-200',
    'border-scorecard-gold-300',
    'border-scorecard-gold-400',
    'border-scorecard-gold-500',
    'border-scorecard-gold-600',
    'border-scorecard-gold-700',
    'border-scorecard-gold-800',
    'border-scorecard-gold-900',
    'hover:bg-scorecard-green-50',
    'hover:bg-scorecard-green-700',
    'hover:bg-scorecard-green-800',
    'hover:bg-scorecard-gold-600',
    'hover:border-scorecard-green-300',
    'hover:border-scorecard-gold-300',
    'font-scorecard',
    'font-heading'
  ]
} 