# SQLite configuration (temporary for deployment)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: bullpen_cup_app_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || ENV['USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  variables:
    timezone: 'America/Chicago'

test:
  adapter: postgresql
  encoding: unicode
  database: bullpen_cup_app_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || ENV['USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  variables:
    timezone: 'America/Chicago'

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>
    template: template0
  cache:
    adapter: postgresql
    encoding: unicode
    database: bullpen_cup_app_production_cache
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['CACHE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate
    template: template0
  queue:
    adapter: postgresql
    encoding: unicode
    database: bullpen_cup_app_production_queue
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
    template: template0
  cable:
    adapter: postgresql
    encoding: unicode
    database: bullpen_cup_app_production_cable
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
    template: template0
